# Site settings
title: contra-bit
subtitle: the basic unit against information
email: liam@contra-bit.com
description: contra-bit is a website dedicated to conform to the integrity of data <br/> simply because information exits, there needs to be a polar opposite
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://contra-bit.github.io/forty-jekyll-theme" # the base hostname & protocol for your site
author: Liam Hurwitz
city: Bremen
state: Bremen
zip_code: 28211
country: Deutschland
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://fb.me/liamhurwitz1
github_url: https://github.com/contra-bit
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+LiamHurwitz
instagram_url: https://instagram.com/_liam97
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

# Google services
google-analytics: UA-28488117-2
